### ISSUE TITLE
Solution not working for me

### ISSUE THREAD

**Issue by asapsmc** [ctrahey/m1-tensorflow-config#1]
Hi! Just leaving here this comment, as I was unable to make your solution work for me (I also have been trying to install tensorflow-macos in my Mac M1 without success), and you said in Apple support to leave you a comment here.

I followed your recipe with success, but when I try to run my code I get the following error:
```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/machine/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/machine/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/machine/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/machine/Projects/finetune-asp/src/problem_BLSTM.py", line 113, in <module>
    main()
  File "/Users/machine/Projects/finetune-asp/src/problem_BLSTM.py", line 108, in main
    simple_BLSTM(dataset)
  File "/Users/machine/Projects/finetune-asp/src/problem_BLSTM.py", line 79, in simple_BLSTM
    train_db = pickle.load(open('%s/%s.pkl' % (PKL_PATH, dataset), 'rb'))
  File "/Users/machine/Projects/finetune-asp/src/definitions.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/site-packages/matplotlib/rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/site-packages/matplotlib/colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/site-packages/matplotlib/scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/site-packages/matplotlib/ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "/Users/machine/miniforge3/envs/tf25/lib/python3.9/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
```

**Comment by ctrahey** [comment]
Thanks for the comment. I just got my M1 Max delivered, so I will be trying to replicate this very soon, and I'll keep you posted, hopefully updating the resources here to make them more reliable.
