### ISSUE TITLE
matplotlib fails to install on Monterey

### ISSUE THREAD

**Issue by nkalupahana** [ctrahey/m1-tensorflow-config#2]
Gives this error, on installing requirements.txt:

```
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/8f/76rrcm815qqd8qqymc9tz7vh0000gn/T/pip-install-avaigmg_/matplotlib_b26f98b24b6547d1bfb02ff6b57609d0/setup.py", line 258, in <module>
      setup(  # Finally, pass this all along to distutils to do the heavy lifting.
    File "/Users/nisala/miniforge3/envs/tf25/lib/python3.9/site-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/Users/nisala/miniforge3/envs/tf25/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/nisala/miniforge3/envs/tf25/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/nisala/miniforge3/envs/tf25/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/nisala/miniforge3/envs/tf25/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/nisala/miniforge3/envs/tf25/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp39', 'cp39', 'macosx_11_0_arm64')
  ----------------------------------------
  ERROR: Failed building wheel for matplotlib

```

**Comment by juan-crimsonmacaw** [comment]
I'm having the same issue here. Did you manage to find a way around it? Thanks!
